source 'https://rubygems.org'
ruby '2.1.5'

gem 'puma', '2.10.2'
gem 'mina'
gem 'foreman'

gem 'eldr'
gem 'eldr-action',     github: 'eldr-rb/eldr-action'
gem 'eldr-rendering',  github: 'eldr-rb/eldr-rendering'
gem 'eldr-sessions'
gem 'eldr-assets',     github: 'eldr-rb/eldr-assets'
gem 'eldr-responders', github: 'eldr-rb/eldr-responders'

gem 'stripe'
gem 'kramdown'
gem 'rouge'
gem 'slim',              '3.0.1'
gem 'omniauth-github',   '1.1.2'
gem 'redis-rack',        '1.5.0'
gem 'require_all',       '1.3.2'
gem 'octokit'
gem 'opal', '0.7.1'
gem 'sprockets', '2.12.3'
gem 'sprockets-sass', '1.3.1'
gem 'bourbon', '3.2.4'
gem 'build-your-own-sinatra', github: 'BuildYourOwnSinatra/build-your-own-sinatra.gem'

group :test do
  gem 'rake',             '10.4.2'
  gem 'rspec',            '3.1.0'
  gem 'rubocop',          '0.28.0'
  gem 'rack-test',        '0.6.2'
  gem 'stripe-ruby-mock', github: 'rebelidealist/stripe-ruby-mock'
  gem 'ffaker',           require: 'ffaker'
  gem 'factory_girl'
  gem 'shoulda-matchers'
  gem 'webmock'
end
